GET http://localhost:3001/api/info

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/10

###
DELETE  http://localhost:3001/api/persons/1

### 
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name" : "brad",
  "number" : "2222"
}